# This workflow is responsible for:
# - publishing artifacts to Maven Central
# - building and publishing javadocs to the git repository.
# It is triggered when a version tag is pushed (by semantic-release).

name: publish

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:
    # Allow this workflow to be triggered manually

jobs:
  publish-release:
    name: publish-release
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to push to gh-pages branch
      pages: write     # Required for GitHub Pages
      id-token: write  # Required for OIDC

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Java
        id: setup-java
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'adopt'
          cache: 'maven'
          # Configure ~/.m2/settings.xml
          server-id: ossrh
          server-username: OSSRH_USERNAME
          server-password: OSSRH_PASSWORD
          # Import GPG key into build agent's local keystore
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: GPG_PASSPHRASE

      - name: Set artifact version to ${{ github.ref_name }}
        run: mvn -B versions:set -DnewVersion=${{ github.ref_name }} -DgenerateBackupPoms=false

      - name: Build and Generate Javadocs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO_SLUG: ${{ github.repository }}
          GH_TAG: ${{ github.ref_name }}
        run: |
          mvn -B clean install -DskipTests
          mvn -B javadoc:aggregate
          build/publishJavadocGHA.sh

      - name: Publish to Maven Central
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GPG_KEYNAME: ${{ secrets.GPG_KEYNAME }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          mvn -B deploy -DskipTests -P central
